apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: apigw-aws
spec:
  # Link Composition to a specific XR and version
  compositeTypeRef:
    apiVersion: example.com/v1
    kind: xapigw
  resources:
    - name: apigw-vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        metadata:
          labels:
            type: vpc
        spec:
          forProvider:
            cidrBlock: 10.0.0.0/16
            region: ap-southeast-1
            enableDnsHostnames: true
            enableDnsSupport: true
            tags:
              Name: apigw-vpc
              Environment: staging
          providerConfigRef:
            name: aws-admin
      patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map: 
                SG: "ap-southeast-1"
                US: "us-east-1"
                EU: "eu-north-1"
        - fromFieldPath: spec.parameters.env
          toFieldPath: spec.forProvider.tags.Environment
          transforms:
            - type: map
              map: 
                staging: "staging"
                preprod: "preprod"
                production: "production"
    - name: apigw-public-subnet
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            tier: public
        spec:
          forProvider:
            cidrBlock: 10.0.1.0/24
            region: ap-southeast-1
            vpcIdSelector:
              matchControllerRef: true
            tags:
              Name: apigw-public-subnet-1
              Environment: staging
          providerConfigRef:
            name: aws-admin
      patches:
        - fromFieldPath: spec.parameters.env
          toFieldPath: spec.forProvider.tags.Environment
          transforms:
            - type: map
              map: 
                staging: "staging"
                preprod: "preprod"
                production: "production"
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map: 
                SG: "ap-southeast-1"
                US: "us-east-1"
                EU: "eu-north-1"
    - name: apigw-private-subnet
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            tier: private
        spec:
          forProvider:
            cidrBlock: 10.0.2.0/24
            region: ap-southeast-1
            vpcIdSelector:
              matchControllerRef: true
            tags:
              Name: apigw-private-subnet-1
              Environment: staging
          providerConfigRef:
            name: aws-admin
      patches:
        - fromFieldPath: spec.parameters.env
          toFieldPath: spec.forProvider.tags.Environment
          transforms:
            - type: map
              map: 
                staging: "staging"
                preprod: "preprod"
                production: "production"
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map: 
                SG: "ap-southeast-1"
                US: "us-east-1"
                EU: "eu-north-1"
    - name: apigw-secgrp
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            region: ap-southeast-1
            vpcIdSelector:
              matchControllerRef: true
            description: ApiGW Access SG
            tags:
              Name: apigw-secgrp
              Environment: staging
          providerConfigRef:
            name: aws-admin
      patches:
        - fromFieldPath: spec.parameters.env
          toFieldPath: spec.forProvider.tags.Environment
          transforms:
            - type: map
              map: 
                staging: "staging"
                preprod: "preprod"
                production: "production"
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map: 
                SG: "ap-southeast-1"
                US: "us-east-1"
                EU: "eu-north-1"
    - name: apigw-instance
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            region: ap-southeast-1
            ami: ami-0464f90f5928bccb8
            instanceType: t2.micro
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                tier: public
            tags:
              Name: apigw-instance
              Environment: staging
          providerConfigRef:
            name: aws-admin
      patches:
        - fromFieldPath: spec.parameters.env
          toFieldPath: spec.forProvider.tags.Environment
          transforms:
            - type: map
              map: 
                staging: "staging"
                preprod: "preprod"
                production: "production"
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map: 
                SG: "ap-southeast-1"
                US: "us-east-1"
                EU: "eu-north-1"
        - fromFieldPath: spec.parameters.env
          toFieldPath: spec.forProvider.instanceType
          transforms:
            - type: map
              map: 
                staging: "t2.nano"
                preprod: "t2.micro"
                production: "t2.medium"
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.ami
          transforms:
            - type: map
              map: 
                SG: "ami-0b825ad86ddcfb907"
                US: "ami-04cb4ca688797756f"
                EU: "ami-0b0d560d43e65a601"