apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-admin
spec:
  projectID: crossplane-398302
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-account
      key: creds